name = "vpn-bot"
main = "src/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[[d1_databases]]
binding = "DB"
database_name = "vpn-bot-db"
database_id = "fad0b2ee-46d1-491f-b85a-09c48f930fad"
